title: Caravel
email: contact@caravel.co.in
description: >- # 
  We ship beautiful, fully-tested applications for your organization.
keywords: 
  caravel, caravel tech, caravel ai, machine learning company, top ai companies, ai tech, ai consultancy, 
  ai software consultancy, caravel one27 enterprises pvt ltd, caravel one27, caravel.co.in, digital studio
baseurl: ""
url: "https://caravel.co.in"
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
